### PR TITLE
Qw123wh tablet number row

### LINKED ISSUE #244: "Always show number row" doesn't work for English (US) (Dvorak)
"Always show number row" doesn't work and switching to the numbers/symbols button on the very bottom left will result in a glitch that will not let the user switch back to the letters. I'm on GrapheneOS

### LINKED ISSUE #328: Always Show Number Row doesn't work for colemak mod-dh
When I used normal qwerty keyboard the number row would be always visible but switching to colemak mod-dh it is only visible while looking at special characters.

Words cannot express how thankful I am to now be able to use colemak mod-dh on my phone. You all are saints. Keep up the fantastic work :)

### LINKED ISSUE #406: Toggling Number row ON is not working on tablets
Toggling `Number row` ON is not working on tablets. 
(The dedicated Emoji key is not also behaving the same. But I am unsure about the emoji key, as there is a persistent emoji button on the keyboard for tablets.)

**Steps to reproduce**
1. Go to _OpenBoard settings_
2. Toggle `Number row` ON form _Preferences_ (also `Show emoji key`)
3. Check keyboard on any text field

**Behaviour**
There should be a dedicated row for numbers on the keyboard, but there would not.

**Emulator**
Name: 13.5_Freeform_API_30
Android version: 11.0
API level: 30
Resolution: 2560 × 1440 hdpi

### LINKED ISSUE #498: No number row
App version: 1.4.4

Android version: 10

On the previous version, there is a number row on the top, while on 1.4.4 the row is gone. I have the "number row" choice in the setting select but this doesn't add the number row back.

### PR DESCRIPTION
**Pull request by qw123wh**
@MajeurAndroid @dslul Hello I have partially solved the problem of the number line on tablets, take a look, however on some tablets like mine when I press the button "?123" sometimes you don't click there are bugs. Check it out and make some changes

Fixes #498
Fixes #406 
Fixes #328
Fixes #244

### CODE REVIEW

**Comment by qw123wh** [comment]
it is still buggy at times but the number line now appears correctly

**Comment by MajeurAndroid** [comment]
@qw123wh looks good, can you describe more precisely the bugs that remain ?

**Comment by qw123wh** [comment]
practically with the row of numbers enabled, when you press the "? 123" key it does not always take the click, you have to click at the bottom left, in the next few days I want to do some tests.  Practically the implementation of the row number on openboard is taken from indic keyboard, in fact even there there is the same problem/bug on the tablet, the test I want to do is to try to re-implement the row of numbers through simple keyboard commits, in fact there is no is this problem / bug.

**Comment by qw123wh** [comment]
@MajeurAndroid start merging this to solve #498 #406 #328 #244 ,then we will try to fix those microbugs when clicking the "? 123" button

**Comment by MajeurAndroid** [comment]
@qw123wh don't worry I have planned to take a look into this, I now where the issue is coming from, and your on the right path but I want to fix this for every other keyboards at the same time.
Also I want to reproduce your bug before merging.

**Comment by qw123wh** [comment]
@MajeurAndroid Ok anyway the bug is this shown through screenrecord, as you can see if you click on the bottom left it works, in the center it doesn't. To reproduce this bug you can simply through android studio select a tablet from avd manager for example on android studio I have selected pixel c with android 10 and the bug even if in a less evident way also occurs ther

https://user-images.githubusercontent.com/59417474/156002957-59444011-e6e7-426a-88f9-8d20a4d0c0f6.mp4

**Comment by MajeurAndroid** [comment]
@qw123wh ok thanks, we definetely need to fix this before merging.

**Comment by qw123wh** [comment]
@MajeurAndroid do you know the path of that key "? 123" 

in which file does that key appear?  Maybe somewhere in the layout?

**Comment by MajeurAndroid** [comment]
@qw123wh have a look at rowkeys_qwerty4.xml, it should help you.

**Comment by MajeurAndroid** [comment]
For some reason, the issue is coming from the symbols keyboard not having the same row count as alphabet keyboard. I'll merge this and push a fix. Thanks @qw123wh.

**Pull request merged**
