### PR TITLE
Enhance german layout

### LINKED ISSUE #79: Show numbers first in pop-up or allow to choose
On the German Keyboard, German Umlauts are the primary selection, when long-pressing keys. That  is, at least for me, a unusal behaviour, as numbers from 1-10 are shown on the same keys in small font in the upper right corner, so I expect a number to appear. 

This behaviour makes it very difficult to type numbers fast.

**Possible solutions:**
1. use the behaviour of the english keyboard
2. invent a selection to choose the primary pop-up keys (and then adjust the character that is shown in the upper right corner on the keys)
3. introduce a german keyboard with Umlauts as extra keys (some keyboard styles of other keyboards have this)

Screenshots to reproduce the behaviour:
**German Keyboard**
signal-attachment-2020-03-20-103948

**English Keyboard**
signal-attachment-2020-03-20-103903

Thank you very much for offering this keyboard!

### PR DESCRIPTION
**Pull request by kojid0**
I've managed to fix #79 and additional enhancements (I deleted letters that are not available in German language).

Not sure whether I was allowed to edit `KeyboardTextsTable.java` because in the first lines it says 

```
* !!!!! DO NOT EDIT THIS FILE !!!!!
 *
 * This file is generated by tools/make-keyboard-text. The base template file is
 *   tools/make-keyboard-text/res/src/com/android/inputmethod/keyboard/internal/
 *   KeyboardTextsTable.tmpl
 *
 * This file must be updated when any text resources in keyboard layout files have been changed.
 * These text resources are referred as "!text/<resource_name>" in keyboard XML definitions,
 * and should be defined in
 *   tools/make-keyboard-text/res/values-<locale>/donottranslate-more-keys.xml
```

But I was not able to find such a path.

Anyways, I have tested it successfully and it works fine. Unless you get thousands of errors now while compiling the app, you should be safe to merge.

### CODE REVIEW

**Comment by dslul** [comment]
> But I was not able to find such a path.

You can find it here https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/master/tools/make-keyboard-text/

Are you sure those additional keys need to be deleted?

**Comment by kojid0** [comment]
They don't necessarily need to be deleted but those keys don't exist in German language so it actually doesn't make sense to keep them for the German keyboard layout.

It might be a general discussion since there are also letters for English keyboard layout that don't exist in native English language. 
I guess you're Italian, so have you ever used some of these letters `å æ ã ę ē ë ù í į ô õ  (and more)`? They just make the keyboard too complex IMO.
Also, SwiftKey doesn't show the letters I deleted in it's German keyboard.

**Comment by dslul** [comment]
They could be useful if you type words in other languages. Do you know how GBoard handles this? Also, in those are the only characters shown in SwiftKey, you need to switch keyboard to type in another language?

**Comment by Glitchy-Tozier** [comment]
I wouldn't quite call this an enhancenent, it's more of an alternative.
Personally (i'm a german-speaker myself)
- I'd prefer it if ü and ö showed up first instead of 7 and 9.
- If i need to use numbers a lot, i can enable the new numbers-row.
- Also i wouldn't want to loose all the other special letters. Even though i don't particularly often use ė, ā, ò, etc, they don't bother me and i don't want to loose access to them.

So I suggest that if those changes were to be implemented, there should be a way to toggle them on/off. 
The default should be the fully-featured keyboard to avoid people thinking that this keyboard just can't write those special numbers.

**Comment by kojid0** [comment]
> They could be useful if you type words in other languages. Do you know how GBoard handles this? Also, in those are the only characters shown in SwiftKey, you need to switch keyboard to type in another language?

Don't have/use GBoard and cannot install easily because I don't have Play Services installed.
Yes, you have to switch language in order to access letters that don't exist in the currently selected language.

> I'd prefer it if ü and ö showed up first instead of 7 and 9.

But as stated in #183, it doesn't make much sense to show 7 as secondary key when it is actually ü. Again, I checked SwiftKey and they show 7 as secondary while ü is third. 


I don't know what the plans are for the close future of openboard but I'd probably wait for @dslul until he implements multi-language recognition. Then we can discuss again about this "enhancement".

**Comment by Glitchy-Tozier** [comment]
To avoid having two discussions at once, I answered on #79

**Comment by kojid0** [comment]
When I usually try to solve problems, I first think about how I would solve it by myself, then how others solved it and then I compare the solutions and debate with others to make good decisions.
I personally think, and that's my personal feeling, that I don't ever need the characters. So after that I looked how the big tech companies (which invest millions of dollars into user studies) made it. And I made a PR in order to see what other people think about this proposal. 
I do agree that, in some rare cases, those letters are needed. But what's the point of having lots of different keyboard layouts for each language if they only differ in spell check (and maybe switched Y and Z)?
Another idea: split keyboard-layout and spell check. Layout can be a full featured layout with all characters available, if needed. Or a simple one which is enough for 99,99% of the time. Spell check: one language or select multiple languages at once (to do in #167)

**Comment by MajeurAndroid** [comment]
I think this is fixed in cae0b9e4bc1bcb430f6b764f7b1c50ba0f84f631 with the addition of de-DE locale. @Glitchy-Tozier @kojid0 can you check this ?

**Comment by MajeurAndroid** [comment]
As the changes have been done in a generated file, they cannot be merged. I'll close this PR for now. If changes are still necessary, they need to be done following [these](https://github.com/openboard-team/openboard#how-to-edit-keyboard-texts) steps.

**Pull request closed without merging**
