### PR TITLE
One-handed mode feature

### LINKED ISSUE #13: One hand mode
It would be nice if we have one hand mode and adjustable height. Having swipe typing will make it perfect FOSS keyboard. The first release looks promising thank you for bringing FOSS keyboard Android doesn't have proper FOSS keyboard. Hope imp features are added in New releases

### LINKED ISSUE #229: Feature Request: Text Editing, One-Handed Mode, Floating.
I think these three features are essential for keyboards. 
Screenshot_2020_1123_013121

### LINKED ISSUE #523: Amoled theme with borders + one hand mode
Please make an amoled theme with borders like one in the GBoard, i just can't use one without the borders
Photo:
https://ibb.co/DGXbkJ9
dark mode OpenBoard theme looks not as good as this theme in GBoard.
and i really need one hand mode - with large phone it feels so bad to use keyboard without one hand mode

### PR DESCRIPTION
**Pull request by MajeurAndroid**
This needs to be tested, especially on non qwerty configs (because I never use them :)). Feel free to comment with your feedbacks and, if needed, some screenshots.
You'll find an APK to test under the "Checks" tab, inside the artifact menu.

The amount of width reduction in one-handed mode is currently 86%, I only tested this on a regular phone. This value can (and must) be adapted to other configurations, such as tablets. Feel free to provide some feedbacks about how it feels on other devices.

Here is a preview:
ezgif-2-0a66ae60b3

Fixes #13
Partially fixes #229
Fixes #523

@SosPosos @hiru12 @kojid0 @mad1mystic @qw123wh you guys might be interested by this.

### CODE REVIEW

**Comment by qw123wh** [comment]
hi, I can't find the apk

**Comment by MajeurAndroid** [comment]
@qw123wh you'll find it there:
capture

**Comment by qw123wh** [comment]
@MajeurAndroid I download a file called “APK.zip” the problem is that it doesn't let me extract it.  Publish an apk as a pre-release or send a link.  I also tried to compile it with Android studio but I couldn't

**Comment by qw123wh** [comment]
@MajeurAndroid to extract the archive "APK.zip" it asks me for a password, what is the password?

**Comment by MajeurAndroid** [comment]
@qw123wh if by "extracted" you meant install the apk, it should be fixed now. Try to re-download the apk, it should be signed. For the password, I have no idea what you're talking about, the archive is a regular zip.

**Comment by qw123wh** [comment]
@MajeurAndroid  it is a file .zip , but it is password protected.  Try to download this .zip file yourself, then try to extract it and it will ask you for a password

**Comment by dslul** [comment]
> @MajeurAndroid it is a file .zip , but it is password protected. Try to download this .zip file yourself, then try to extract it and it will ask you for a password

I have no issue with the archive, it works fine

**Comment by qw123wh** [comment]
@MajeurAndroid @dslul I had a problem I could not download the file correctly, I don't know what caused it sorry, now everything is ok. 
Back to the app, I tested it on 3 smartphones, and on 1 tablet.  On the following smartphones “Redmi 9A android 9 (miui), redmi note 8 android 10 aosp, redmi note 7 android 12 aosp.  The Tablet is Samsung galaxy s2 (8 inch version) android 7.

On the three smartphones listed, one-handed mode works well in portrait mode, while in landscape mode it doesn't work.

On Samsung s2 tablet it does not work neither in landscape nor in portrait mode, and in addition, the number line does not appear.  I only have this android tablet, I don't know if it works fine on other tablets

**Comment by MajeurAndroid** [comment]
@qw123wh thanks, can you elaborate and describe what is not working on your tablet ? Maybe with screenshots.

**Comment by qw123wh** [comment]
@MajeurAndroid This is the behavior of the app on the tablet ( the number line option is also enabled, but it doesn't work) Screenrecorder

https://user-images.githubusercontent.com/59417474/155022160-90a430c5-9003-4f12-acba-4066397e520d.mp4

**Comment by qw123wh** [comment]
@MajeurAndroid perhaps this is better seen
https://user-images.githubusercontent.com/59417474/155024295-d6b12264-b17d-4e9b-8102-d22176136aeb.MP4

**Comment by MajeurAndroid** [comment]
@qw123wh thanks, this is now fixed in 500c8eb. This one was tricky, the bug causing the issue is from Google itself ! I am really surprised it has not been fixed before!
For those interested, here is the bug in Google's android repo: https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/master/java/src/com/android/inputmethod/keyboard/internal/MoreKeySpec.java#301

**Comment by qw123wh** [comment]
@MajeurAndroid perfect I tested the new apk and now everything works fine even on the tablet. Google makes many disasters, fixes bugs in proprietary apps (gboard) and ditches aosp counterparts

**Comment by jnnkB** [comment]
Since the lastest release is from January and this PR only got merged in March, I'm pretty sure its not included. But you should be able to use the APK from the artifacts of last Github Actions run: https://github.com/openboard-team/openboard/actions?query=branch%3Amaster.

**Comment by ItsRogueRen** [comment]
> Since the lastest release is from January and this PR only got merged in March, I'm pretty sure its not included. But you should be able to use the APK from the artifacts of last Github Actions run: https://github.com/openboard-team/openboard/actions?query=branch%3Amaster.

I still seem to be missing a setting for one-handed mode even with that latest build

**Comment by Helium314** [comment]
> I still seem to be missing a setting for one-handed mode even with that latest build

See the video in the first post: try a long press on comma key

**Comment by MajeurAndroid** [comment]
@ItsRogueRen it's avilable as shown in the gif inside PR's description, can you try with an english keyboard ? If it is still not working, you might not have the latest release.

**Comment by ItsRogueRen** [comment]
> @ItsRogueRen it's avilable as shown in the gif inside PR's description, can you try with an english keyboard ? If it is still not working, you might not have the latest release.

I got it, it didn't actually install the first time around and I didn't realize

**Pull request merged**
