### PR TITLE
Added back Bangla (Bangladesh) (Akkhor) layout

### PR DESCRIPTION
**Pull request by RHJihan**
This layout was the default layout for Bengali (Bangladesh) on OpenBoard. As Akkhor is not widely used by Bengali users, it was replaced with a popular one. #401

Akkhor layout is introduced again if there exist some users who prefer this.

### CODE REVIEW

**Comment by MajeurAndroid** [comment]
@RHJihan thanks for your contribution. Can you provide more details about the changes you made and give examples of the new newly added layout ?

**Comment by RHJihan** [comment]
@MajeurAndroid, description updated.

**Comment by MajeurAndroid** [comment]
@RHJihan thank you, I'll merge this.
@Oymate these changes bring back Akkhor keyboard.

**Comment by Oymate** [comment]
Please make a release soon, thanks

**Pull request merged**
