### PR TITLE
Settings update

### LINKED ISSUE #135: [BUG] Add input style icon almost invisible
## The bug

The "add" icon in `‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‏‎‏‎‏‏‏‏‏‏‏‏‏‏‏‏‏‎‏‎‎‏‏‏‏‏‏‎‏‎‎‏‏‎‏‎‏‎‎‎‏‎‏‎‏‎‎‎‎‎‎‎‎‎‎‏‏‎‎‎‏‎‏‎‎‎‏‏‏‏‎‏‏‏‎‎‎‎Custom input styles` (to the right) is _too light_ to be visible.
The problematic file(s) is [ic_add_circle_white](https://raw.githubusercontent.com/dslul/openboard/master/app/src/main/res/drawable-hdpi/ic_add_circle_white_24dp.png).

light_ico

## Additional Details
- consider what happens when using dark mode
- I looked for a comparison how other apps do it, but wasn't able to find one
However I noticed it is common to do the plus in the bottom right as a circle:

This might be a possible better way to do it.

### PR DESCRIPTION
**Pull request by MajeurAndroid**
This needs a bit of testing to make sure I missed nothing. You'll find an APK for testing attached to this PR in the "Artifacts" menu under the "Checks" tab.

Here is an example for appearance settings:
screenshot_2022-01-29-16-04-17

Fixes #135

### CODE REVIEW

**Comment by Pentaphon** [comment]
Are the default custom input styles still there or are they removed by default. When I install Openboard on a new device as English user, I guess French custom style already enabled by default, which I don't need.

**Comment by MajeurAndroid** [comment]
I don't think this behaviour comes from the modifications in this PR. Can you reproduce this on the production app?

**Comment by Pentaphon** [comment]
Yes, I cleared the storage on the latest version of Openboard from the Play Store to bring the app back to its original state right now and this is what I get as the default settings as an English (from my device) user. Note how "German (Qwerty) and French (Qwertz)" are enabled by default. That setting should be completely empty when you first install the app or clear the app data but that's not the case. It's been like this since Openboard first appeared on the app store and I just remembered to report this when I saw your PR just now. 

default

**Comment by MajeurAndroid** [comment]
Alright, I think you should report this in a dedicated issue.

**Comment by Pentaphon** [comment]
> Did you noticed any other bugs when testing this PR?

I haven't tested this PR. I just wanted to see if you noticed/fixed it in this PR before reporting it, which I just did here! https://github.com/openboard-team/openboard/issues/514

**Comment by MajeurAndroid** [comment]
IMO we can merge this even if I am the only one to have runned tests, if there are bugs, they must be minor ones and will be fixed later on.

**Comment by jnnkB** [comment]
Hey @MajeurAndroid, while working on #526 I also tested the new settings a bit.
First of all they look great and I really like the new structure. But I noticed that when opening Languages in the OpenBoard Settings and navigating back I end up in the android settings in System/Languages & input. Is that intended? If so the Languages list item should maybe make that apparent.

**Comment by MajeurAndroid** [comment]
@jnnkB thanks for your feedback. This is an issue that was already there, I think it depends on the settings app configuration, which often depends on vendor implementation of android.

**Comment by jnnkB** [comment]
I just tried the version on fdroid and there navigating back seems to work as expected

**Pull request merged**
